apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Zdrx/5kB7STsF5PbQCDP7pBjA9it7K3n+gj1tO82/SezlE3FpUmJfQ==,iv:7FUagdtGjx3m4r/5Obf4Ue8slKX7gWifd1ct5FjPrZw=,tag:cSpj1Uw5LAVxWZicpLZstg==,type:str]
sops:
  age:
    - recipient: age1032qnksttng5z3qw0png7wv55dpdjgdqgljz05kkxsf3qajgfqjq0jyqm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaFJFT0MzRGI0TnkwNklj
        ZmV2R2ZQSWRxdFlhOVhFWDdpMlJSb1ZpZ3pjCmxpL2xZVXlhdDd4c1RzVHlmYU9D
        OVJqUHVSQnl4WkpXeERIZVBKem03bncKLS0tIEZBVm4vQ0pleDYyV2w4WGVrNXMw
        Nll6ZEs4TW1ZV0k4MHhzQ1BxM3dTSjQKvgcyMNe+l4p3cwRJP/xQIdi5a1x9sCXE
        RlZABDj1qKZC1/9N4RsW4M9dgplNVNKUXYpmIDtu5dXfYkgq8bed1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T00:46:47Z"
  mac: ENC[AES256_GCM,data:JrfYmxGA3vr/HMPonXzgXz4szR+NYunCilSou5kq7BithFEZ1rdyhctVD/CFDpkcT3rdSvZNAsxEZYmqmJ/hLmLsGd41G0ESu+U6TJRjL8l2i6FklYIFABAvSvxfWEHBR1/zZm3bIE1j86/4aRfXRW4luSZK7vvTwME6LZqsmlE=,iv:PRHqtX8gD65zcwzQH65RaTgOZrlOtKJwDTUBbttdPkc=,tag:2TkofUyHUa+FrsdzX9Dheg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
