apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+nJaeFOb0VYUug==,iv:Xczx7WS0QFMPfCQFuh5uDhvpq+zxDvGFAp0s9K42vBY=,tag:SG3/UV+KMTmT5XxXGXmUiA==,type:str]
sops:
  age:
    - recipient: age1032qnksttng5z3qw0png7wv55dpdjgdqgljz05kkxsf3qajgfqjq0jyqm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNzR0aDROQ1U4emlia3pF
        Y3FCYytsYjlmcTZZTmVCWEhjNDNFdUZVR3hBClpjV0k2TXExU3dWOGJpRXFGT0d2
        eUo3ZlRrZnZxaXZBTFFXOHgzWnc0VFkKLS0tIHYrZENzeG5IWFAyR2d4WCs2aDJI
        enNidm1BbU1QM1VScXhrUkwwblkvUDAKQIZz/MxQS0mvDNI2YkQt/QkV4xsc4E0o
        hwgpFgnBRsIOBzKa98HDs9rLY3k3mmHrf5uDCPwQtseFrHq2xqYecQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T00:46:47Z"
  mac: ENC[AES256_GCM,data:eKq+CCSllkQxrwsaVzDxK+ILNjy28rWoOLtDmPUr/nvDUdxvve7VVeKvFn/QqTx2SRizQj9CG0Ocng84c9wabsAVd6gvrQhXVCL3NV7H83OwLPJVNA63oSFnNETqS3Z5TU65AYF09CC+Qwq2FALyNIxMFA5cH8W8oYU21MKl6h4=,iv:7a26NqhRLJFHIro+5TDD2LrZxs77ExUbPxPbsZIHs74=,tag:X5EGIhB/lvFbbRzILV5oKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
