---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./release.yaml
configMapGenerator:
  - name: glance-configmap
    files:
      - glance.yml=./config/glance.yml
