apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:nS3uK8A90VHejbCeH23g/DWQKeAwOg9rG0jlrOQvfRg=,iv:H2EeRBMQYrCD8RNEFMG0S+231py5cLns2QEnJEBAeDI=,tag:YBNBMxMMXblWpYEEmcckRg==,type:str]
sops:
  age:
    - recipient: age1032qnksttng5z3qw0png7wv55dpdjgdqgljz05kkxsf3qajgfqjq0jyqm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeG5YTGYyandoS3hDcTUx
        dU5Yc1p4NWExUGZpTUY0L1lqMzYzYmh5SndBCmZJRmpPRFNKVjl6WS9HNERtU3Uw
        ZUFia3dYVy9rZG00RS8zNDdwQysrOGcKLS0tIExUZ3F2NVhRdm1lOTRjQ2wwTGc5
        eUxzMVlpNUp0aDRQUEhRenNMRFV3MDgKQozGptxLZCr9uiXosbomwVNHT0Y01ROf
        WuwlpOlef36WCduDWJHpZ/LPe/BPCG8lK3tZU0jwNyL637ZAzJ/5vg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T00:46:47Z"
  mac: ENC[AES256_GCM,data:G/5GSHa6wapO5yIrcnEDJTdE7b3LqLO2h3MFmdn3rRF8NKIhqgKXg9Xuzmzae7knX9tFNQIs8FPrN5G97qRguHq9l+a3qyvHSfsvKNe34S0YKqwdoqWHqzuKaO5d0b91dgXZjop+DruCGQZVs9QMeWr/LD1YUHvDhWtxWnesF1I=,iv:39AyBDFxpB/V6Krawwa8gbxx1yISU9iUlofCxQxOWs8=,tag:PyhmIedXjmQr2LH2W0pDuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
