apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:XmO4fZtg6KEnbg5dI4iaisifMQAhs1VGn7msOchlptOm6boXvK1n4lOnXT0hW9UCAoDG/VoxROzMN9numcD54wYjANtNTlDNtvMCANyuUIJAnFi1zbYPL1d0CmhW9KGHcV9WngZiAQSecJj4UBjlNEhux22H7IOjEGPdrGjus2VdRcSPTczT+A+paQDCe/8l1/yuShVS4Z7H+Sy9sYRquff81lMDzeNO52FGo0zErMAY+1kL,iv:Uw/tvaVtr+9LAYeU2p0qe4iH248muq0ja03wGiwSrkI=,tag:pIXPrRUFBeH3ZmWwh3PtWQ==,type:str]
sops:
  age:
    - recipient: age1032qnksttng5z3qw0png7wv55dpdjgdqgljz05kkxsf3qajgfqjq0jyqm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQThlZnJXZ3ZHTDU4YWNJ
        a3MwbDFPOXpwR2VxVGh6eGlZeURTNlpHS2dRClBwbE9qeVMvU3BqVUVKNHd3UEFD
        MmxUdzZCbUhYaGZ1Y2huanhXbE1NUU0KLS0tIEU2bWNtcUR0VmJnOWV0Y3UzL05X
        WENXYnNEaTVsem9BbHhnaUFCNHpiNncKoks0hwQ4fcPpNKX0SeJ8WdkmK3aCDEJg
        i8mMcIObMD+LYnUtDVJpuhY43d6TR+N3fkv6LnV0fgvErc+9lfoYJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T00:46:47Z"
  mac: ENC[AES256_GCM,data:yu9E4lyOTRXPNJc4wr0BUFoujXCSBJdZWpW3OsagQ5KmV+CXwjaPt5QXNibP4ldnJVcVO2JkZYEbnUB/+eIywm9kyjFXGlQ9fSylZwcGn0xiQX0mlMqFVnU2ExCi3SmM4530lRa+w4WS2McYts5pUtRFqE2U7BozOk4iF1CIb9I=,iv:MBZbaOAytzkc1em98flsG7flDbYCuC9Q1wF6OSND0HU=,tag:Bog5/Uq/QMF6TNiB6u9IAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
