apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Aoc6c3NsNCq5DRrfFJkIz0WumZfFFtK6C2Lqk0XUiI7E/RinRJ+rQQ==,iv:eBFFUuRUxUwmVM4dv+xSG5iSENrOLg6HW0ynyD38ygk=,tag:jjHRmLZJm8qHu0Wu9Qa29w==,type:str]
sops:
  age:
    - recipient: age1032qnksttng5z3qw0png7wv55dpdjgdqgljz05kkxsf3qajgfqjq0jyqm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArb2xZby9EOWRBYi8xR3lX
        RU1lT1BMSUxZUjMxLzlxSG91MHhQTWdheDBNCllMSi9tSUVrS0tPVzJQRGNYcWNI
        c3dvN2pSYW9IWDRBekRkQlZmLy96Z3cKLS0tIGdleUIySnp0YUlYc01ucGhweW1x
        Q0dEYVB5ajZUOXpGVm4yUVRqZkQzb1UKbnTnaADxY8zbJOhai+4YGZeTS1PGoYlK
        P4GEZjS4wSBo3ZoaM+acR9ZdYAbcH2ekeJvxWDo0DQv4f2bugL+JCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T00:46:47Z"
  mac: ENC[AES256_GCM,data:Z6v6raSwvm7Wnb/E0uLgcBq1kbeeFT028yoTDC9hE5NanOY7RfhkFuA5PDsAtEEN78jpJE0KtHZmkLBwJ1Qlu7yWmbKZtkxH6Li9PZuiZfUJBQQ/vRlkt/O+cm/q6BOluo1YMGWAXLqsIiZ6pBu8h4Jqh46IVPROdpel/dvvb7Q=,iv:/4RVah2u2TPVbyKe2CIsvKuCVydLAWOJL73pSWd856Q=,tag:PAwZ1asDvbqxtUy8ilJopQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
